### ISSUE TITLE
Rouge Error 

### ISSUE THREAD

**Issue by tonygracious** [atulkum/pointer_summarizer#10]
I am getting following error while I am running

 'Rouge155' object has no attribute 'convert_and_evaluate'

**Comment by KDercksen** [comment]
Which pyrouge package have you installed? [This one](https://github.com/bheinzerling/pyrouge/blob/master/pyrouge/Rouge155.py#L345) has the function, as you can see; the package is available on PyPI [here](https://pypi.org/project/pyrouge/)
