### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'initial_accumulator_value'

### ISSUE THREAD

**Issue by pengzhi123** [atulkum/pointer_summarizer#15]
training log:
max_size of vocab was specified as 50000; we now have 50000 words. Stopping reading.
Finished constructing vocabulary of 50000 total words. Last word added: chaudhary
Traceback (most recent call last):
  File "training_ptr_gen/train.py", line 150, in <module>
    train_processor.trainIters(config.max_iterations, args.model_file_path)
  File "training_ptr_gen/train.py", line 121, in trainIters
    iter, running_avg_loss = self.setup_train(model_file_path)
  File "training_ptr_gen/train.py", line 57, in setup_train
    self.optimizer = Adagrad(params, lr=initial_lr, initial_accumulator_value=config.adagrad_init_acc)
TypeError: __init__() got an unexpected keyword argument 'initial_accumulator_value'
i use pytorch0.3, tensorflow1.2.
Please help.
Thanks.

**Comment by atulkum** [comment]
Pytorch 0.4 has the required changes. You should use that.

**Comment by pengzhi123** [comment]
> Pytorch 0.4 has the required changes. You should use that.

OK, thanks. I'll try.
