### ISSUE TITLE
what is '$MODEL' in 'start_decode.sh'?

### ISSUE THREAD

**Issue by NinaTian98369** [atulkum/pointer_summarizer#19]
Hello, I am running start_decode.sh, and I got the error for this line:
`model_filename = sys.argv[1]`
The error is **list out of range**, so I went and checked the sys.argv. by calling `print sys.argv` and got : `['training_ptr_gen/decode.py']`. Nothing for sys.argv[1].
In the shell script :
`MODEL= $1`
`python training_ptr_gen/decode.py $MODEL`
But when I type `echo $1`, nothing is returned. 
So I am wondering what is it supposed to be and why did I get this error?
Thanks!

**Comment by jivatneet** [comment]
@NinaTian98369 did you figure this out?
@atulkum Can you give more clarity as to any arguments to be passed while running the scripts?

**Comment by Tinarights** [comment]
Hello,
Could you please tell me the solution?
