### ISSUE TITLE
Decode generating same summery

### ISSUE THREAD

**Issue by Rachnas** [atulkum/pointer_summarizer#2]
Hi,
Thanks for providing Pytorch implementation for summerization. I trained the model on custom data set for ~15000 iterations. On decoding, same summery is generated for all the stories. I am not sure where exactly is the problem in code, still debugging. Any help/suggestion is appreciated.
In beam_search code, there is a comment '#batch should have only one example' where as in BeamSearch constructor, bacther takes batch size same as beam_size(4). Is it correct ?

Thanks

**Comment by atulkum** [comment]
Yes the first iteration of beam search replicate the same prediction for all 4 steps. 
https://github.com/atulkum/pointer_summarizer/blob/master/training_ptr_gen/decode.py#L124

The best way to debug is to step through each line by putting breakpoint in code. An editor like pycharm would help.

**Comment by rainsher** [comment]
I also got the problem and I checked the beam_search results in decode are all the same while the input batch is different. how do you solve it?

**Comment by atulkum** [comment]
In decode beam search batch should have only one example
https://github.com/atulkum/pointer_summarizer/blob/master/training_ptr_gen/decode.py#L109
https://github.com/atulkum/pointer_summarizer/blob/master/data_util/batcher.py#L226

**Comment by xilinniao123** [comment]
i have 2 questions:
why beam_size must equals batch_size?why sample in one batch must same?

**Comment by atulkum** [comment]
The whole batch is used as beam for one instance. This way the decoding is made parallel on gpu.
