### ISSUE TITLE
What does the variable (training) mean?

### ISSUE THREAD

**Issue by qlwang25** [atulkum/pointer_summarizer#20]
https://github.com/atulkum/pointer_summarizer/blob/a6620efa39ae02d1f938121abb2a8c9c29e4eac0/training_ptr_gen/model.py#L152

Hi!
I can not found the definition of  the variable ```self.training```.
Could you  give  some explanations.
Thanks a lot.

**Comment by atulkum** [comment]
This variable is coming from nn.Module, at the time of training it is True otherwise false.
.eval() wil set this variable to false.
https://github.com/atulkum/pointer_summarizer/blob/a6620efa39ae02d1f938121abb2a8c9c29e4eac0/training_ptr_gen/model.py#L209
