### ISSUE TITLE
run the train

### ISSUE THREAD

**Issue by BigwhiteRookie** [atulkum/pointer_summarizer#21]
Thanks for your code, but I have a question: when I run the train.py , one error : AttributeError: 'generator' object has no attribute 'next', i dont understand it , the system show it at the batcher.py 209

**Comment by atulkum** [comment]
Which version of python your are using? I have tested it on python 2.7

**Comment by BigwhiteRookie** [comment]
Thank you for your reply. I use Python 3.6 ，but I have some modification to fit this version.  Is this problem also because the version is different? How should I modify it?

**Comment by TalSchuster** [comment]
[https://stackoverflow.com/questions/1073396/is-generator-next-visible-in-python-3-0](url)

**Comment by LewPeng97** [comment]
change next to __next__

**Comment by LewPeng97** [comment]
change next to \__next\__()
