### ISSUE TITLE
Ask about loading data

### ISSUE THREAD

**Issue by realjoenguyen** [atulkum/pointer_summarizer#29]
Can I ask why you didn't use dataloader in pytorch for handling data (examples and batch) with num_worker > 0? 

Why do you need to explicitly start threads in class Batcher to load the queue? 

Thank you for your help,

**Comment by realjoenguyen** [comment]
@atulkum still waiting for your reply. Thank you.

**Comment by atulkum** [comment]
I think that was some redundant code which I did not clean. If I remember correctly, I end up using single threaded loader
