### ISSUE TITLE
When training around 8400 iters, got loss=nan

### ISSUE THREAD

**Issue by buptorange** [atulkum/pointer_summarizer#39]
First thanks a lot for releasing the pytorch implementation of pg-network.
When I started training, the output is:
> steps 100, seconds for 100 batch: 45.91 , loss: 8.439692
>steps 200, seconds for 100 batch: 53.07 , loss: 8.152159
>steps 300, seconds for 100 batch: 55.09 , loss: 7.645596
>steps 400, seconds for 100 batch: 51.75 , loss: 7.824278
>steps 500, seconds for 100 batch: 45.38 , loss: 7.567791

However, when it was about 8400 iters, the output is:
>steps 8200, seconds for 100 batch: 57.81 , loss: 7.064022
>steps 8300, seconds for 100 batch: 61.35 , loss: 6.479928
>steps 8400, seconds for 100 batch: 56.97 , loss: nan
>steps 8500, seconds for 100 batch: 61.95 , loss: nan
>steps 8600, seconds for 100 batch: 59.06 , loss: nan

And after that it's all nan. I didn't modify the model or data or preprocess. 
Could you give me some guide or hints to solve this problem?

**Comment by zide05** [comment]
i got this result, too. have you solved this problem, if you do ,how?
