### ISSUE TITLE
How to train the model from last checkpoint saved

### ISSUE THREAD

**Issue by rajeshsahu09** [atulkum/pointer_summarizer#42]
Thanks for your contribution. Sir I have trained the model till 2,70,000 epoch. But due to some reason I have to stop the training there. When saw the loss it was still decreasing. So now I want to train the model again from last checkpoint i.e. 2,70,000. How can I do?

**Comment by atulkum** [comment]
python training_ptr_gen/train.py -m checkpoint-path

**Comment by rajeshsahu09** [comment]
Thank you
