### ISSUE TITLE
Vector encode input extend vocab

### ISSUE THREAD

**Issue by binhna** [atulkum/pointer_summarizer#50]
Hi, I think there is a problem in your code at creating the `enc_input_extend_vocab` for each Example.
Let's say we have 200,000 words in our vocabulary.
In your code, each word in the articles which does not appear in the vocabulary (oov), you will assign this word with new index, which is `index = len(vocabulary) + number_of_new_word_in_this_article`
But you doesn't add this word to the vocabulary. This is the problem. Because let's say in the first example, we have 1 article_oov word is 'mother', you will assign it by 200,001. In the second example, you have 'father' is the article_oov, you will assign 'father' by 200,001 too. If somehow, 2 above examples are in the same batch, then index of 'father' and 'mother' are the same??

**Comment by atulkum** [comment]
The processing for each example is independent.  The additional OOV vocabulary is created for pointers only, so it should only account for that particular oov. Looking at the model code would make it more clear https://github.com/atulkum/pointer_summarizer/blob/5eb298a66b4d3b53adb854ba9b5c82580cf2fa1e/training_ptr_gen/model.py#L181

**Comment by binhna** [comment]
I know you process each example independently, but with any first `article_oov_word` in any example, you would assign its index by `len(vocab) + 1` no matter what is its index in another example. For example:
You have 2 sentences in a batch:
1. Give me the direction to my house
2. Tell me about alexa

And your vocab: [give, me, the, direction, to, my, tell, about], len = 8
After processing, 2 extended_vocab would be:
1. [0, 1, 2, 3, 4, 5, 8] --> 8 is for house
2. [6, 1, 7, 8, -1, -1, -1] --> 8 is for alexa

Is it ok for training?

**Comment by atulkum** [comment]
Yeh that’s how the pointer network work OOV is added to vocabulary just to point in that particular example. The purpose is NOT to extend the overall vocabulary. It would be more clear from the paper.
