### ISSUE TITLE
what's function of the eval.py when i check the train.py ,it does't call the eval.py , save the model directly?

### ISSUE THREAD

**Issue by XuemingQiu** [atulkum/pointer_summarizer#51]
I can't understander what means, can you help me?
Question:
1. what's function of the eval.py?
2. In train.py, it seems not check valid loss ,so what's means about eval.py?
3. what does mean about the 
""
    calc_running_avg_loss() 
""
if I remove it , can I also get the correct answer.

**Comment by atulkum** [comment]
1. what's function of the eval.py?
It evaluate the test data and print the number. https://github.com/atulkum/pointer_summarizer/blob/master/start_eval.sh
2. In train.py, it seems not check valid loss ,so what's means about eval.py?
After training we run eval. This part might explain https://github.com/atulkum/pointer_summarizer#how-to-run-training
3. what does mean about the
calc_running_avg_loss is to smooth our loss so the graph looks reasonable. you can comment it out you will still get the correct answer.
