### ISSUE TITLE
What is the specific implementation of pointer network

### ISSUE THREAD

**Issue by gaozhiguang** [atulkum/pointer_summarizer#58]
I have read the Paper 《Get To The Point Summarization with Pointer-Generator Networks》，the author describes a dynamic vocabulary by copying words from the source , but i don't know how to implementation in code, I tried to read the source code, but I didn't find it. Can someone tell me the specific location in the code?

**Comment by atulkum** [comment]
This is where oov are extracted from each data point. 
https://github.com/atulkum/pointer_summarizer/blob/master/data_util/batcher.py#L42

Here is the model use this oov for pointer network
https://github.com/atulkum/pointer_summarizer/blob/master/training_ptr_gen/model.py#L187
