### ISSUE TITLE
Retraining model cause optimizer duplicate parameter error

### ISSUE THREAD

**Issue by Sixy1204** [atulkum/pointer_summarizer#61]
Hello

When I use python3 train.py -m model_path to retrain the model, it throws a  UserWarning: optimizer contains a parameter group with duplicate parameters; in future, this will cause an error; see github.com/pytorch/pytorch/issues/40967 for more information
  super(Adagrad, self).__init__(params, defaults)
And then the code stop running. I believe it is related to reloading model trained parameters. 
How can I fix it?
thank you

**Comment by atulkum** [comment]
The code was written for python 2.7, it won't be a tough task to upgrade it to pyhton 3. Sorry for the confusion.

**Comment by Sixy1204** [comment]
> The code was written for python 2.7, it won't be a tough task to upgrade it to pyhton 3. Sorry for the confusion.

Sorry, my bad. When retraining, user should set max_iteration bigger than log iter.

thx！ lol

**Comment by Wenjun-Peng** [comment]
> The code was written for python 2.7, it won't be a tough task to upgrade it to pyhton 3. Sorry for the confusion.

I wonder why you share parameters of encoder to decoder:
`decoder.embedding.weight = encoder.embedding.weight`
and it cause same problem mentioned above:
`UserWarning: optimizer contains a parameter group with duplicate parameters; in future, this will cause an error; see github.com/pytorch/pytorch/issues/40967 for more information`
