### ISSUE TITLE
c_0 should be is a zero vector

### ISSUE THREAD

**Issue by raheelqader** [atulkum/pointer_summarizer#7]
In Abigail See's paper, it says that c_0 is a zero vector, but based on the following line, c_0 in your code is equivalent to a_0 or maybe I'm missing something.
https://github.com/atulkum/pointer_summarizer/blob/454a2f6f10865531f724cbe5064a927d66dfa1b7/training_ptr_gen/model.py#L122

**Comment by atulkum** [comment]
c_0 is  zero vector only in case of training. For decoding (self.training == False) c_0 is same as a_0 as you mention.
Here is the relevant code in Abigail See's repo
https://github.com/abisee/pointer-generator/blob/a7317f573d01b944c31a76bde7218bcfc890ef6a/attention_decoder.py#L140

**Comment by raheelqader** [comment]
you're right thanks.
