### ISSUE TITLE
Index of Out Bound Error in doing scatter_add when we have OOV words

### ISSUE THREAD

**Issue by tim5go** [atulkum/pointer_summarizer#8]
https://github.com/atulkum/pointer_summarizer/blob/454a2f6f10865531f724cbe5064a927d66dfa1b7/training_ptr_gen/model.py#L192

I am using another dataset to train the model, I observed that if we have OOV words, the value in `enc_batch_extend_vocab` could be larger than the length of `vocab_dist_`, which causing like index out of bound error.

Is it better to patch those wordID to zero if it is larger than the size of Vocab?

**Comment by atulkum** [comment]
Yes you are right.
