### ISSUE TITLE
Reason for Accepting Repeated Identical Examples in Decoding Phase

### ISSUE THREAD

**Issue by tim5go** [atulkum/pointer_summarizer#9]
https://github.com/atulkum/pointer_summarizer/blob/5eb298a66b4d3b53adb854ba9b5c82580cf2fa1e/data_util/batcher.py#L228
Is there a particular reason why we send a repeated examples as a batch in the decoding phase?
But not a batch of different examples?

Is it because for `pack_padded_sequence`
https://github.com/atulkum/pointer_summarizer/blob/5eb298a66b4d3b53adb854ba9b5c82580cf2fa1e/training_ptr_gen/model.py#L55
it only accepts sorted sequences?

**Comment by atulkum** [comment]
The reason is we want to keep "beam size == batch size". at the start every row in a beam has a ```<s>``` token.
And then we pick the output from the beam having highest score.

**Comment by tim5go** [comment]
https://github.com/atulkum/pointer_summarizer/blob/454a2f6f10865531f724cbe5064a927d66dfa1b7/training_ptr_gen/model.py#L96

I also observed if `beam_size = 4` and `batch_size = 32`, it will throw dimension mismatch error here, is it the reason you mentioned?

It is quite weird I have to set them identical.

**Comment by atulkum** [comment]
To make the code simpler we run 1 beam per batch. You can code multiple beam per batch too, just need to process every beam separately.
